name: show
description: Showcase your flutter widgets.
version: 0.5.0
author: Rob Halff <rob.halff@gmail.com>
homepage: https://github.com/dartlib/show
repository: https://github.com/dartlib/show.git

environment:
  sdk: ">=2.2.2 <3.0.0"

executables:
  show:

dependencies:
  process_run: ^0.10.3
  flutter_svg: ^0.14.2
  analyzer: '>=0.35.0 <0.38.0'
  args: ^1.5.2
  code_builder: ^3.2.0
  dart_style: ^1.2.9
  glob: ^1.1.7
  meta: ^1.1.7
  path: ^1.6.4
  flutter:
    sdk: flutter
  flutter_tools:
    sdk: flutter

  build: ^1.2.0
  build_runner_core: ^4.1.0
  logging: ^0.11.3+2
  watcher: ^0.9.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/logo.png

