name: show
description: Showcase your flutter widgets.
version: 0.2.1
author: Rob Halff <rob.halff@gmail.com>
homepage: https://github.com/dartlib/show
repository: https://github.com/dartlib/show.git

environment:
  sdk: ">=2.2.2 <3.0.0"

executables:
  show:

dependencies:
  meta: ^1.1.6
  args: ^1.5.2
  path: ^1.6.2
  glob: ^1.1.7
  analyzer: '>=0.35.0 <0.38.0'
  code_builder: ^3.2.0
  dart_style: ^1.2.9
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

